<#
.SYNOPSIS
    Generates an RSA key pair for signing the iDM3 update catalogue.

.DESCRIPTION
    Writes the private key OUTSIDE this repository and the public key into keys/ for
    committing. The public key is compiled into iDM3, so it is pinned: the application
    trusts this key and nothing else, which is what allows the catalogue to be hosted
    publicly without trusting the host.

    Generate TWO keys before the first release - one Active, one Standby. Both are pinned
    in iDM3. Without a standby key already deployed in the field, a lost or compromised
    active key cannot be replaced on installations that are offline or unattended.

    RSA-3072 with SHA-256. Keys are stored in the .NET XML format because iDM3 reads
    them with RSA.FromXmlString on .NET Framework 4.8. That format is read and written
    here by RsaXml.ps1 rather than by ToXmlString, so this script also runs on macOS and
    Linux - RSACng and the XML helpers are Windows-only.

.PARAMETER PrivateKeyPath
    Where to write the private key. Must be outside this repository. Move it to offline
    storage - a hardware token or an encrypted volume held by two people - once written.

.PARAMETER Role
    Active or Standby. Determines the file names only; both keys are equally valid.

.EXAMPLE
    .\tools\New-SigningKey.ps1 -PrivateKeyPath D:\keys\idm3-catalog-active.private.xml -Role Active
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$PrivateKeyPath,

    # Development produces a key for testing the pipeline end to end. Build-Catalog and
    # Test-Catalog both warn loudly when a development key is in play, because a
    # catalogue signed by one must never be published.
    [ValidateSet('Active', 'Standby', 'Development')]
    [string]$Role = 'Active',

    [ValidateRange(2048, 8192)]
    [int]$KeySize = 3072,

    [switch]$Force
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'RsaXml.ps1')

$repoRoot = Split-Path -Parent $PSScriptRoot
$keysDir  = Join-Path $repoRoot 'keys'

# --- Refuse to write private key material anywhere inside the repository -------------
$privateFull = [System.IO.Path]::GetFullPath(
    [System.IO.Path]::Combine((Get-Location).Path, $PrivateKeyPath))
$repoFull = [System.IO.Path]::GetFullPath($repoRoot).TrimEnd('\') + '\'

if ($privateFull.StartsWith($repoFull, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to write a private key inside the repository ($privateFull). Choose a path on offline storage."
}

if ((Test-Path -LiteralPath $privateFull) -and -not $Force) {
    throw "A private key already exists at $privateFull. Pass -Force only if you are certain you want to replace it - any catalogue signed with the old key stops verifying."
}

$parent = Split-Path -Parent $privateFull
if (-not (Test-Path -LiteralPath $parent)) {
    throw "The directory $parent does not exist."
}

# --- Generate -------------------------------------------------------------------------
Write-Output "Generating RSA-$KeySize key pair ($Role)..."
$rsa = New-RsaKey -KeySize $KeySize

try {
    $privateXml = ConvertTo-RsaXml -Rsa $rsa -IncludePrivateParameters
    $publicXml  = ConvertTo-RsaXml -Rsa $rsa

    $parameters = $rsa.ExportParameters($false)
    $sha256     = [System.Security.Cryptography.SHA256]::Create()
    try {
        $fingerprint = -join ($sha256.ComputeHash($parameters.Modulus) | ForEach-Object { $_.ToString('X2') })
    }
    finally { $sha256.Dispose() }

    # --- Private key, locked to the current user --------------------------------------
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($privateFull, $privateXml, $utf8NoBom)

    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    $acl = Get-Acl -LiteralPath $privateFull
    $acl.SetAccessRuleProtection($true, $false)
    foreach ($existing in @($acl.Access)) { [void]$acl.RemoveAccessRule($existing) }
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        $identity, 'FullControl', 'None', 'None', 'Allow')))
    Set-Acl -LiteralPath $privateFull -AclObject $acl

    # --- Public key, for committing ----------------------------------------------------
    if (-not (Test-Path -LiteralPath $keysDir)) {
        New-Item -ItemType Directory -Path $keysDir -Force | Out-Null
    }

    $name       = "idm3-catalog-$($Role.ToLowerInvariant())"
    $publicPath = Join-Path $keysDir "$name.public.xml"
    [System.IO.File]::WriteAllText($publicPath, $publicXml, $utf8NoBom)

    $metaPath = Join-Path $keysDir "$name.fingerprint.txt"
    @(
        "Role        : $Role"
        "Algorithm   : RSA-$KeySize, SHA-256"
        "Fingerprint : $fingerprint"
        "Generated   : $([DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ'))"
        "Generated by: $identity"
    ) | Set-Content -LiteralPath $metaPath -Encoding utf8
}
finally {
    $rsa.Dispose()
}

Write-Output ""
Write-Output "Private key : $privateFull   (ACL restricted to $identity)"
Write-Output "Public key  : $publicPath"
Write-Output "Fingerprint : $fingerprint"
Write-Output ""
Write-Output "Next:"
Write-Output "  1. Move the private key to offline storage. Do not leave it on this machine."
Write-Output "  2. Commit keys\$name.public.xml and keys\$name.fingerprint.txt."
Write-Output "  3. Pin the public key in iDM3 and record the fingerprint in keys\README.md."
Write-Output "  4. If this was the Active key, generate the Standby key now - not later."
